[general]
import = []


[keyboard]
bindings = [

  # copy and paste
  { key = "C", mods = "Control|Shift", action = "Copy" },
  { key = "P", mods = "Control|Shift", action = "Paste" },

  # font
  { key = "+", mods = "Control|Shift", action = "IncreaseFontSize" },
  { key = "_", mods = "Control|Shift", action = "DecreaseFontSize" },

  # disable following window management options, zellij will do it.
  # { key = "T", mods = "Control|Shift", action = "CreateNewWindow" },
  # { key = "Q", mods = "Control|Shift", action = "Quit" },

  { key = "Q", mods = "Control|Shift|Alt", action = "Quit" },
]
